baseURL = 'https://example.com/'
languageCode = 'en-us'
title = "indiedeck"
copyright = 'ultimateownsz'
enableRobotsTXT = true

[outputs]
home = ['html']
section = ['html', 'rss', 'json']
page = ['html']

[menus]
[[menus.main]]
name = 'Notes'
pageRef = '/notes'
weight = 20
[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 30
[[menus.main]]
name = 'Graph'
pageRef = '/graph'
weight = 40

[markup]
[markup.highlight]
noClasses = false
style = 'tokyonight-night'

[markup.goldmark]
[markup.goldmark.parser]
[markup.goldmark.parser.attribute]
block = true

[params]
dateFormat = ':date_long'
showGraph = true

[params.author]
name = 'John Doe'
email = 'johndoe@example.com'

[params.home]
showRecentPosts = true
recentPostsLimit = 3
showRecentNotes = true
recentNotesLimit = 5

[params.notes]
pageSize = 20
showCategoryFilter = true

[params.footer]
creativeCommonsLicense = 'by_sa'
showCreativeCommonsIcons = true
showThemeCredit = false

[params.robotstxt]
blockCC = false
blockAI = false

[frontmatter]
default = 'yaml'